---
- name: Install Docker and Docker Compose on Ubuntu
  hosts: radius
  become: true
  gather_facts: true

  tasks:
    - name: Update package cache and install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - psmisc
        - sysstat
        - git

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker APT repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

    - name: Update package cache after adding Docker repository
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker-ce docker-ce-cli containerd.io
        state: present

    - name: Run Docker Hello World
      command: docker run hello-world
    - name: Create Docker group
      group:
        name: docker

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      when: ansible_user != 'root'

    - name: Install Docker Compose
      command: >
        curl -sSL https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Make Docker Compose executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
