- name: Update packages
  hosts: remote_hosts
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Update packages
      apt:
        upgrade: safe
        autoremove: true
        autoclean: true
